ValueSet: FXREQBusinessProcesses
Title: "Functional Requirements Business Processes"
Description:  "Value Set for Functional Requirements Business Processes. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = true
* include codes from system FXREQBusinessProcesses

