ValueSet: FXREQCategories
Title: "Functional Requirement Categories"
Description:  "Value Set for Functional Requirement Categories. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = true
* include codes from system FXREQCategories

