CodeSystem: FXREQBusinessProcesses
Title: "Functional Requirements Business Processes"
Description:  "CodeSystem for Functional Requirements Business Processes. Autogenerated from DAK artifacts"
* ^experimental = true
* ^caseSensitive = false
* ^status = #active
* #A "Registration"
* #B "Screening"
* #C "Diagnosis"
* #D "TB Treatment"
* #E "TB preventive treatment (TPT)"
* #F "Referral"
* #G "Aggregate reporting and data use"

